language: node_js

 node_js:
   - 16.15.1

 cache:
   directories:
     - ./client/node_modules

 before_script:
   - npm install --prefix path-to-your-frontend-folder

 script:
    - npm run test --prefix path-to-your-frontend-folder
